[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/ecommerce-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/auth/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
